<a href="https://colab.research.google.com/github/NevermindGust/IA_Python_Aulas/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#cria matriz unidimencional - X
a = np.array([12, 34, 26, 18, 10])
print(a)
#indica o tipo da matriz
print(a.dtype)

[12 34 26 18 10]
int64


In [3]:
#cria matriz bidimencional - X e Y
b = np.array([[7, 2, 23], [12, 27, 4], [5, 34, 23]])
print(b)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [4]:
c = np.zeros([4, 3])
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#cria matriz zerada com '1' na diagonal principal
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
#gerar matriz com numeros aleatorios
e = np.random.random(5)
print(e)

[0.75048461 0.24111989 0.13261241 0.9065174  0.42607042]


In [15]:
#matriz bidimencional
f = np.array([[17, 22, 43], [27, 25, 14], [15, 24, 32]])
print(f)
#exibe elemento especifico
print(f[0][1])

#exibe tamanho das dimencoes da matriz f
print(f.shape)

#valor maximo da matriz
print(f.max())

#valor minimo da matriz
print(f.min())

#soma dos valores
print((f.sum()))

#valor medio
print(f.mean())

#desvio padrao - standard deviation
print(f.std())

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)
43
14
219
24.333333333333332
8.615231988880057
